Repository IntellectualSites/PlotSquared, pull requests merged in 2021-11, with the labels that each got.

#3305 Don't display the default plot title if on a server-plot, unless configured otherwise.
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
Labels: Hacktoberfest, Feature

#3319 fix for issue 3317 (flag untrusted-visit not working)
  Core/src/main/java/com/plotsquared/core/command/Visit.java
Labels: Ready for Review, Bugfix

#3309 Use a more player friendly done message on restricted building
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitEntityUtil.java
  Core/src/main/resources/lang/messages_en.json
Labels: hacktoberfest-accepted, Enhancement

#3315 perf: get rid of guice overhead when accessing the plot area manager
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
Labels: Enhancement

#3308 Split configuration for teleport on claim/auto
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: hacktoberfest-accepted, Enhancement

#3303 Schematic paths are configurable
  Core/src/main/java/com/plotsquared/core/command/Area.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotManager.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
Labels: Ready for Review, hacktoberfest-accepted, Bugfix

#3300 Better deciding of heights to use for generation and schematics
  Core/src/main/java/com/plotsquared/core/backup/PlayerBackupProfile.java
  Core/src/main/java/com/plotsquared/core/command/Load.java
  Core/src/main/java/com/plotsquared/core/command/SchematicCmd.java
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotManager.java
  Core/src/main/java/com/plotsquared/core/generator/HybridGen.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotManager.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: hacktoberfest-accepted, Enhancement

#3345 Fixes #3344, Wrong iterator algorithm in PlotRangeIterator
  Core/src/main/java/com/plotsquared/core/plot/PlotId.java
  Core/src/test/java/com/plotsquared/core/plot/PlotRangeIteratorTest.java
Labels: Ready for Review, Bugfix

#3351 style: Add missing bracket for `deny` example
  Core/src/main/java/com/plotsquared/core/command/Deny.java
Labels: documentation
