Repository IntellectualSites/PlotSquared, pull requests merged in 2021-12, with the labels that each got.

#3334 Add -`Post` events firing after operational plot events
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/command/Claim.java
  Core/src/main/java/com/plotsquared/core/command/Delete.java
  Core/src/main/java/com/plotsquared/core/command/Merge.java
  Core/src/main/java/com/plotsquared/core/command/Owner.java
  Core/src/main/java/com/plotsquared/core/command/Unlink.java
  Core/src/main/java/com/plotsquared/core/events/post/PostPlayerAutoPlotEvent.java
  Core/src/main/java/com/plotsquared/core/events/post/PostPlotChangeOwnerEvent.java
  Core/src/main/java/com/plotsquared/core/events/post/PostPlotDeleteEvent.java
  Core/src/main/java/com/plotsquared/core/events/post/PostPlotMergeEvent.java
  Core/src/main/java/com/plotsquared/core/events/post/PostPlotUnlinkEvent.java
  Core/src/main/java/com/plotsquared/core/events/post/package-info.java
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
  Core/src/main/java/com/plotsquared/core/util/task/AutoClaimFinishTask.java
Labels: Feature

#3360 build: Switch PRTree GAV to our deployment
  Bukkit/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Ready for Review, internal

#3357 Move from JUnit 4 to JUnit 5
  Core/src/test/java/com/plotsquared/core/configuration/caption/ClickStripTransformTest.java
  Core/src/test/java/com/plotsquared/core/plot/FlagTest.java
  Core/src/test/java/com/plotsquared/core/plot/PlotRangeIteratorTest.java
  Core/src/test/java/com/plotsquared/core/plot/PlotVersionTest.java
  Core/src/test/java/com/plotsquared/core/synchronization/LockRepositoryTest.java
  build.gradle.kts
Labels: tests

#3375 fix: Ignore the use flag for liquid placement/removal
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix, Ready for merge

#3374 fix: Standardize projectile permissions
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
  Core/src/main/java/com/plotsquared/core/permissions/Permission.java
Labels: Enhancement

#3373 Fix more MM builder issues
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
  Core/src/main/java/com/plotsquared/core/command/Inbox.java
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/Placeholders.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotId.java
  Core/src/main/java/com/plotsquared/core/util/PlayerManager.java
  Core/src/main/java/com/plotsquared/core/util/helpmenu/HelpObject.java
  Core/src/main/java/com/plotsquared/core/util/helpmenu/HelpPage.java
  Core/src/main/resources/lang/messages_en.json
Labels: internal

#3400 fix: Strip redundant space at flag collection
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: Bugfix

#3388 Send user-friendly message when players attempt to enter a plot they are denied from
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix

#3399 fix: npe thrown in entity spawn listener
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
Labels: Bugfix

#3389 Drop informational guava and JB annotations
  Core/src/main/java/com/plotsquared/core/plot/comment/CommentManager.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/util/AnnotationHelper.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
Labels: chore

#3414 Fix: Account for mutability of plot objects when sending move/swap success messages
  Core/src/main/java/com/plotsquared/core/command/Move.java
  Core/src/main/java/com/plotsquared/core/command/Swap.java
Labels: Bugfix

#3409 Refactor: Replace Rörledning with Cloud-Services
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/inject/modules/PlotSquaredModule.java
  Core/src/main/java/com/plotsquared/core/services/plots/AutoService.java
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore
