Repository IntellectualSites/PlotSquared, pull requests merged in 2022-06, with the labels that each got.

#3646 Remove aggregation of cross module javadocs
  build.gradle.kts
Labels: Ready for merge, Developer

#3648 chore: Address Paper javadoc warnings
  Bukkit/build.gradle.kts
Labels: Ready for merge, chore

#3641 Prevent blocks moving/generating below and above build height
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix, Ready for merge

#3653 build: Switch to bill of materials
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#3661 chore: Update Code of conduct email
  CODE_OF_CONDUCT.md
Labels: skip-changelog

#3643 fix: mob cap counting for each connected plot individually
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
Labels: Bugfix, Ready for merge

#3666 Only load world cofigurations if WorldEdit has fully enabled (safe to do)
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitPlotGenerator.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
Labels: Bugfix, Ready for merge

#3672 docs: Unify WE, P2 and Fawe abbreviations
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/GenChunk.java
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/java/com/plotsquared/core/plot/PlotAreaTerrainType.java
  Core/src/main/java/com/plotsquared/core/plot/flag/types/ListFlag.java
  Core/src/main/java/com/plotsquared/core/queue/ChunkQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/util/RegionManager.java
  Core/src/main/java/com/plotsquared/core/util/RegionUtil.java
  Core/src/main/java/com/plotsquared/core/util/TabCompletions.java
Labels: documentation

#3669 chore: Add tadpole buckets to the list of dispensable items
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Ready for merge, chore

#3668 feat: Add 1.19 music disk to the /plot music GUI
  Core/src/main/java/com/plotsquared/core/command/Music.java
Labels: Feature, Ready for merge

#3657 Ensure forceSync is provided when constructing chunk coordinators
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitChunkCoordinator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/inject/factory/ChunkCoordinatorFactory.java
  Core/src/main/java/com/plotsquared/core/queue/ChunkCoordinatorBuilder.java
  Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java
Labels: Major bug fix, Ready for merge

#3671 Add an on-complete task to PlotArea#mergePlots
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
Labels: Ready for merge, Developer

#3676 fix: Don't publish root directory to maven repository
  build.gradle.kts
Labels: Developer

#3660 Chore: General deprecations
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitWorld.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/fawe/FaweRegionManager.java
  Core/src/main/java/com/plotsquared/core/command/Chat.java
  Core/src/main/java/com/plotsquared/core/command/Load.java
  Core/src/main/java/com/plotsquared/core/command/MainCommand.java
  Core/src/main/java/com/plotsquared/core/command/Save.java
  Core/src/main/java/com/plotsquared/core/events/PlayerAutoPlotEvent.java
  Core/src/main/java/com/plotsquared/core/events/PlayerTeleportToPlotEvent.java
  Core/src/main/java/com/plotsquared/core/permissions/Permission.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/java/com/plotsquared/core/plot/PlotManager.java
  Core/src/main/java/com/plotsquared/core/plot/PlotWorld.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/PlotFlag.java
  Core/src/main/java/com/plotsquared/core/util/MainUtil.java
  Core/src/main/java/com/plotsquared/core/util/PlayerManager.java
  Core/src/main/java/com/plotsquared/core/util/RegExUtil.java
  Core/src/main/java/com/plotsquared/core/util/RegionManager.java
  Core/src/main/java/com/plotsquared/core/util/RegionUtil.java
  Core/src/main/java/com/plotsquared/core/util/TabCompletions.java
  Core/src/main/java/com/plotsquared/core/util/WorldUtil.java
  Core/src/main/java/com/plotsquared/core/uuid/UUIDMapping.java
Labels: chore, v7

#3680 Reset wall filling on clear
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
Labels: Bugfix, Ready for merge

#3658 Address deprecations in queue/generation code
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BlockStatePopulator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitPlotGenerator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/DelegatePlotGenerator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/LegacyBlockStatePopulator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/GenChunk.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitRegionManager.java
  Core/src/main/java/com/plotsquared/core/command/Area.java
  Core/src/main/java/com/plotsquared/core/generator/AugmentedUtils.java
  Core/src/main/java/com/plotsquared/core/generator/HybridGen.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/generator/IndependentPlotGenerator.java
  Core/src/main/java/com/plotsquared/core/generator/SingleWorldGenerator.java
  Core/src/main/java/com/plotsquared/core/queue/BlockArrayCacheScopedQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/ChunkQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/ZeroedDelegateScopedQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/util/ChunkManager.java
Labels: Ready for merge, chore, v7

#3686 docs: Publish javadocs to GH actions
  .github/workflows/build.yml
  Bukkit/build.gradle.kts
Labels: documentation

#3673 refactor: replace usages of switch over keyed enums
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener117.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: chore

#3706 chore: Replace AnnotationHelper class
  Bukkit/build.gradle.kts
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/GenChunk.java
  Core/build.gradle.kts
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
  Core/src/main/java/com/plotsquared/core/location/UncheckedWorldLocation.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/queue/BlockArrayCacheScopedQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/util/AnnotationHelper.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
  build.gradle.kts
Labels: Ready for merge, chore

#3705 Better handling of offline projectile shooters
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
Labels: Bug, Ready for merge

#3704 Use single PlotListener instance
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix, Ready for merge

#3659 Update to new Spigot generation API
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitPlotGenerator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/DelegatePlotGenerator.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/generator/AugmentedUtils.java
  Core/src/main/java/com/plotsquared/core/generator/HybridGen.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/generator/IndependentPlotGenerator.java
  Core/src/main/java/com/plotsquared/core/generator/SingleWorldGenerator.java
  Core/src/main/java/com/plotsquared/core/plot/BlockBucket.java
  Core/src/main/java/com/plotsquared/core/plot/world/DefaultPlotAreaManager.java
  Core/src/main/java/com/plotsquared/core/plot/world/PlotAreaManager.java
  Core/src/main/java/com/plotsquared/core/plot/world/SinglePlotAreaManager.java
  Core/src/main/java/com/plotsquared/core/util/ChunkManager.java
Labels: Feature, Ready for merge, v7

#3708 Minor cleanup of the plot analyze code
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
Labels: chore

#3711 Show old flag value in remove command
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
Labels: Bugfix, Ready for merge

#3709 Ignore cancelled projectile launch events
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
Labels: Developer
