Repository IntellectualSites/PlotSquared, pull requests merged in 2022-05, with the labels that each got.

#3581 Add Plot flag for projectiles
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/ProjectilesFlag.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#3599 Update my name
  build.gradle.kts
Labels: chore, skip-changelog

#3585 Improvements to /plot list command
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/resources/lang/messages_en.json
Labels: Enhancement, Ready for merge

#3612 Implement chunkObject into queueing
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java
Labels: Feature, Ready for merge

#3586 Add ability to disable random Mojang uuid API calls
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
Labels: Feature, Ready for merge

#3620 Make y location of homes absolute for `Plot#getHomeSynchronous` too
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: Bugfix, Ready for merge

#3601 Correctly use yIndex when regenerating plots in certain world configurations
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitRegionManager.java
Labels: Bugfix, Ready for merge

#3613 Deprecations to Queues
  Core/src/main/java/com/plotsquared/core/queue/ChunkQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/ScopedQueueCoordinator.java
Labels: Ready for merge, chore

#3618 Fix plot analysis
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpiryTask.java
  Core/src/main/java/com/plotsquared/core/queue/BlockArrayCacheScopedQueueCoordinator.java
Labels: Major bug fix, Ready for merge

#3622 Update to Paper 1.18.2
  Core/src/main/java/com/plotsquared/core/configuration/caption/Caption.java
  gradle/libs.versions.toml
Labels: dependencies

#3615 Fix generation of augmented/partial worlds when single worlds are enabled
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitSetupUtils.java
  Core/src/main/java/com/plotsquared/core/util/SetupUtils.java
Labels: Bugfix, Ready for merge

#3614 Fix lag caused when generating augmented worlds with roads
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitAugmentedGenerator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitChunkCoordinator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/generator/AugmentedUtils.java
  Core/src/main/java/com/plotsquared/core/queue/BasicQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/DelegateQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/ScopedQueueCoordinator.java
Labels: Bugfix, Major bug fix, Ready for merge

#3520 Replace legacy color codes in flag examples
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/DescriptionFlag.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/GreetingFlag.java
Labels: Bugfix, Ready for merge

#3633 Update PaperMC repository endpoint
  Bukkit/build.gradle.kts
Labels: chore

#3632 Change maven group and artifact ID
  Bukkit/build.gradle.kts
  build.gradle.kts
  settings.gradle.kts
Labels: Developer

#3533 Don't expose jcip and findbugs annotations to the world on runtime
  .gitignore
  Bukkit/build.gradle.kts
Labels: Ready for Review, Developer

#3639 Kick players on merged plots appropriately
  Core/src/main/java/com/plotsquared/core/command/Deny.java
Labels: Bugfix, Ready for merge

#3642 Update Readme SVG
  .idea/icon.svg
  README.md
  plotsquared-logo.png
Labels: skip-changelog
