Repository IntellectualSites/PlotSquared, pull requests merged in 2022-09, with the labels that each got.

#3787 Invoke -parameters on compile time
  build.gradle.kts
Labels: chore

#3627 feature: add flag for beacon effects of other plots
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/SpigotListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/java/com/plotsquared/core/player/ConsolePlayer.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/BeaconEffectsFlag.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#3803 Add GLOW_BERRIES to VineGrowFlag
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Enhancement

#3788 Add allay to animals
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitUtil.java
Labels: Feature

#3816 plots.auto.mega fix for #3815
  Core/src/main/java/com/plotsquared/core/command/Auto.java
Labels: Bugfix
