Repository IntellectualSites/PlotSquared, pull requests merged in 2022-10, with the labels that each got.

#3812 Fix "set block timer" error after "/plot download" with legacy-webinterface setting
  Core/src/main/java/com/plotsquared/core/command/Download.java
Labels: Bugfix

#3818 Improve feedback for invalid patterns
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotWorld.java
Labels: hacktoberfest-accepted, Bugfix

#3819 Only show visible players in `/plot near`
  Core/src/main/java/com/plotsquared/core/command/Near.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: hacktoberfest-accepted, Feature

#3823 refactor: replace guava's Iterables with Java's stream API
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ForceFieldListener.java
Labels: hacktoberfest-accepted, chore

#3822 Update the plot sign when a plot has been purchased
  Core/src/main/java/com/plotsquared/core/command/Buy.java
Labels: hacktoberfest-accepted, Bugfix

#3826 Move license into jar during compile process
  Core/build.gradle.kts
  Core/src/main/resources/LICENSE
Labels: chore

#3821 Deprecate PlotId#copy
  Core/src/main/java/com/plotsquared/core/command/DatabaseCommand.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotId.java
Labels: hacktoberfest-accepted, chore

#3834 Check proper locations on PortalCreateEvent
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix

#3839 chore: Announce releases on Discord
  .github/workflows/announce-release-on-discord.yml
Labels: chore

#3829 Don't kill owned road entities (leashed / named)
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
Labels: Bugfix

#3835 Support MiniMessage in plot-title flag
  Core/src/main/java/com/plotsquared/core/util/StringMan.java
  Core/src/test/java/com/plotsquared/core/plot/FlagTest.java
  Core/src/test/java/com/plotsquared/core/util/StringManTest.java
Labels: Bugfix

#3840 fix: Adjust schematic height logic when pasting and actually set air as well
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotManager.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
Labels: Bugfix

#3843 Ensure all setBlock methods in BlockArrayCacheScopedQueueCoordinator apply the correct offset
  Core/src/main/java/com/plotsquared/core/queue/BlockArrayCacheScopedQueueCoordinator.java
Labels: Bugfix

#3830 Fix 'No resource for locale 'lang' found ' error
  Core/src/main/java/com/plotsquared/core/configuration/caption/load/ClassLoaderCaptionProvider.java
Labels: Bugfix

#3842 fix: adjust nullability checks for shulkers in the kill road mobs task
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
Labels: Bugfix

#3845 feat: Move ExpireManager to Guice by removing legacy IMP references
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/command/DebugExec.java
  Core/src/main/java/com/plotsquared/core/command/Done.java
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/java/com/plotsquared/core/command/Trim.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpiryTask.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
  Core/src/main/java/com/plotsquared/core/util/query/ExpiredPlotProvider.java
Labels: Feature

#3852 Annotate ExpireManager with @Inject
  Core/src/main/java/com/plotsquared/core/command/DebugExec.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
Labels: Bugfix

#3854 fix: account for mismatched road-schematic heights
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
Labels: Bugfix
