Repository IntellectualSites/PlotSquared, pull requests merged in 2022-04, with the labels that each got.

#3558 Deprecate `Load#secToTime()` in favor of `TimeUtil#secToTime()`
  Core/src/main/java/com/plotsquared/core/command/Load.java
  Core/src/main/java/com/plotsquared/core/util/TimeUtil.java
Labels: Ready for Review, chore

#3557 Clean up PlayerCommandPreprocess listener
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Core/src/main/java/com/plotsquared/core/util/RegExUtil.java
Labels: Ready for Review, chore

#3556 Fix: Resolve username in plot entry title when disabling UUID cache
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
Labels: Bugfix

#3572 Fix wall generation missing north side
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotManager.java
Labels: Bugfix

#3571 Fix broken roads on plot delete
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
Labels: Ready for Review, Bugfix

#3575 Update SquirrelID to 0.3.1
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Ready for Review, dependencies

#3577 Emphasize project icon in idea selection
  .gitignore
  .idea/icon.svg
Labels: chore

#3576 Replace jsr305 with spotbugs
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
  gradle/libs.versions.toml
Labels: Ready for Review, chore

#3568 Make y location of homes always absolute
  Core/src/main/java/com/plotsquared/core/command/SetHome.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: Ready for Review, Bugfix

#3590 Set plot biome chunk by chunk
  Core/src/main/java/com/plotsquared/core/util/RegionManager.java
Labels: Feature
