Repository IntellectualSites/PlotSquared, pull requests merged in 2022-01, with the labels that each got.

#3431 ci: Setup auto rebase
  .github/workflows/rebase.yml
Labels: skip-changelog

#3412 fix: Reimplement the "unknown owner" option to plot purge
  Core/src/main/java/com/plotsquared/core/command/Purge.java
  Core/src/main/resources/lang/messages_en.json
Labels: Bugfix

#3417 Fix: use portal corners to test for event cancellation as entity can be null
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix

#3418 Fix: Only send border area exit message once
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix

#3419 Fix: use ownersInclude instead of ownedBy where required
  Core/src/main/java/com/plotsquared/core/command/Cluster.java
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/java/com/plotsquared/core/command/Visit.java
Labels: Bugfix

#3420 Make road flags great again
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
Labels: Bugfix

#3428 Fix: 1.18 uses the same field as 1.17 for mustNotSave
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ChunkListener.java
Labels: Bugfix

#3436 feat: Display explosion particles even after the event got canceled (with setting to control behavior)
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
Labels: Feature

#3432 Fix `/plot music` being able to be used on unclaimed plots
  Core/src/main/java/com/plotsquared/core/command/Music.java
Labels: Bugfix

#3430 Fix for unwanted audio panning
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
Labels: Bugfix

#3447 Sort plugins on `/plot debugpaste` alphabetically
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/command/DebugPaste.java
Labels: Enhancement

#3446 Add 1.18's music disc additions to `/plot music`
  Core/src/main/java/com/plotsquared/core/command/Music.java
Labels: Enhancement

#3451 refactor: Prepare removal of our maven repository
  Bukkit/build.gradle.kts
  Bukkit/src/main/java/com/plotsquared/bukkit/inject/WorldManagerModule.java
  Bukkit/src/main/java/com/plotsquared/bukkit/managers/HyperverseWorldManager.java
  build.gradle.kts
  gradle/libs.versions.toml
Labels: skip-changelog

#3444 Allow restoration of road schematic height calculation behaviour from pre 6.1.4
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotManager.java
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotWorld.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
Labels: Ready for Review, Enhancement

#3457 feat: add worldname to the notify flags
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/resources/lang/messages_en.json
Labels: Enhancement

#3449 Fix: Missing Component returns + plot info on unknown plot owner
  Core/src/main/java/com/plotsquared/core/command/Add.java
  Core/src/main/java/com/plotsquared/core/command/Deny.java
  Core/src/main/java/com/plotsquared/core/command/Owner.java
  Core/src/main/java/com/plotsquared/core/command/Trust.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/Templates.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
  Core/src/main/java/com/plotsquared/core/util/PlayerManager.java
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
Labels: Bugfix

#3461 draft: Address false positives in code style issues
  .lift.toml
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java
  Bukkit/src/main/java/com/plotsquared/bukkit/inject/WorldManagerModule.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener113.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/SingleWorldListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/schematic/StateWrapper.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitInventoryUtil.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/UpdateUtility.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/fawe/FaweSchematicHandler.java
  Core/src/main/java/com/plotsquared/core/player/MetaDataAccess.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/util/EntityUtil.java
Labels: skip-changelog

#3410 feat: plot-title flag value should allow single values
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/PlotTitleFlag.java
  Core/src/main/java/com/plotsquared/core/util/StringMan.java
  Core/src/test/java/com/plotsquared/core/plot/FlagTest.java
  Core/src/test/java/com/plotsquared/core/util/StringManTest.java
Labels: Feature

#3463 PlayerInteractEvent does not necessarily interact with a block
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix

#3452 feat: unknown owner(s) for plot expiry
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpiryTask.java
  Core/src/main/java/com/plotsquared/core/queue/ChunkQueueCoordinator.java
Labels: Feature

#3470 Unify true/false style in `@return` javadoc
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/PlotVersion.java
  Core/src/main/java/com/plotsquared/core/backup/BackupManager.java
  Core/src/main/java/com/plotsquared/core/command/Command.java
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
  Core/src/main/java/com/plotsquared/core/configuration/ConfigurationSection.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/CaptionMap.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/ChatFormatter.java
  Core/src/main/java/com/plotsquared/core/database/AbstractDB.java
  Core/src/main/java/com/plotsquared/core/database/Database.java
  Core/src/main/java/com/plotsquared/core/events/PlayerPlotDeniedEvent.java
  Core/src/main/java/com/plotsquared/core/events/PlayerPlotHelperEvent.java
  Core/src/main/java/com/plotsquared/core/events/PlayerPlotTrustedEvent.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/java/com/plotsquared/core/plot/PlotManager.java
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
  Core/src/main/java/com/plotsquared/core/plot/comment/CommentInbox.java
  Core/src/main/java/com/plotsquared/core/util/ChunkUtil.java
  Core/src/main/java/com/plotsquared/core/util/PremiumVerification.java
  Core/src/main/java/com/plotsquared/core/util/RegionManager.java
  Core/src/main/java/com/plotsquared/core/util/SchematicHandler.java
  Core/src/main/java/com/plotsquared/core/util/query/PlotQuery.java
  Core/src/main/java/com/plotsquared/core/uuid/UUIDService.java
Labels: documentation

#3469 Address dangling `@see` tags
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/LocaleHolder.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/world/PlotAreaManager.java
Labels: documentation

#3471 Add `@since` annotation for v6 API changes
  Bukkit/src/main/java/com/plotsquared/bukkit/managers/MultiverseWorldManager.java
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/command/Chat.java
  Core/src/main/java/com/plotsquared/core/command/Save.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/CaptionUtility.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/ComponentTransform.java
  Core/src/main/java/com/plotsquared/core/events/PlayerAutoPlotEvent.java
  Core/src/main/java/com/plotsquared/core/events/PlayerAutoPlotsChosenEvent.java
  Core/src/main/java/com/plotsquared/core/events/PlayerTeleportToPlotEvent.java
  Core/src/main/java/com/plotsquared/core/events/PlotClaimedNotifyEvent.java
  Core/src/main/java/com/plotsquared/core/events/TeleportCause.java
  Core/src/main/java/com/plotsquared/core/permissions/PermissionHolder.java
  Core/src/main/java/com/plotsquared/core/permissions/PermissionProfile.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/java/com/plotsquared/core/plot/PlotManager.java
  Core/src/main/java/com/plotsquared/core/plot/PlotTitle.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/PlotFlag.java
  Core/src/main/java/com/plotsquared/core/plot/world/SinglePlotArea.java
  Core/src/main/java/com/plotsquared/core/queue/ChunkCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/util/MainUtil.java
  Core/src/main/java/com/plotsquared/core/util/Permissions.java
  Core/src/main/java/com/plotsquared/core/util/SchematicHandler.java
  Core/src/main/java/com/plotsquared/core/util/SetupUtils.java
  Core/src/main/java/com/plotsquared/core/util/TabCompletions.java
  Core/src/main/java/com/plotsquared/core/util/query/PlotQuery.java
Labels: documentation

#3474 Fix the set block timer if the queue is not empty
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
Labels: Bugfix

#3472 Fix: `Plot#getOwner` can be nullable, and redstone may be present on unowned plots
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix

#3466 fix: Don't ommit flag int input in no permission message
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
Labels: Bugfix

#3476 Separate linked javadocs per module
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
Labels: documentation

#3468 Align plugin's java version with API java version - Java 17
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Enhancement

#3482 Switch to generated wiki
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  Core/src/main/java/com/plotsquared/core/command/PluginCmd.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  README.md
Labels: documentation

#3479 fix: Always call plot events through the event dispatcher
  Core/src/main/java/com/plotsquared/core/command/Done.java
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
  Core/src/main/java/com/plotsquared/core/command/Music.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
Labels: Bugfix
