Repository IntellectualSites/PlotSquared, pull requests merged in 2022-02, with the labels that each got.

#3475 fix: NPE on unavailable music discs on lower versions
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitInventoryUtil.java
  Core/src/main/java/com/plotsquared/core/command/Music.java
  Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java
  Core/src/main/java/com/plotsquared/core/plot/PlotItemStack.java
  Core/src/main/java/com/plotsquared/core/util/InventoryUtil.java
Labels: Bugfix

#3490 Display "/plot help" categories only, if the player has permission to access these commands
  Core/src/main/java/com/plotsquared/core/command/CommandCategory.java
  Core/src/main/java/com/plotsquared/core/command/Help.java
  Core/src/main/java/com/plotsquared/core/util/helpmenu/HelpMenu.java
Labels: Feature

#3497 Don't execute selected presets with prices if economy is disabled
  Core/src/main/java/com/plotsquared/core/components/ComponentPresetManager.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#3489 Restore ability to use PlaceholderAPI in greeting and farewell flag
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/resources/lang/messages_en.json
Labels: Bugfix

#3496 Don't open the component GUI if the actor has no permission for a specific component
  Core/src/main/java/com/plotsquared/core/components/ComponentPresetManager.java
  Core/src/main/resources/lang/messages_en.json
Labels: Bugfix

#3487 Cancel block placement if the block consists of two block states
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix

#3501 Fix shulkers teleporting on the road
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
Labels: Bugfix

#3519 Bump `actions/setup-java` to 3.0.0
  .github/workflows/build.yml
Labels: Renovate

#3518 Replace delombok-ed equals and hashCode methods
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitWorld.java
  Core/src/main/java/com/plotsquared/core/plot/PlotWorld.java
  Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/PlotFlag.java
  Core/src/main/java/com/plotsquared/core/uuid/UUIDMapping.java
Labels: chore
