Repository IntellectualSites/PlotSquared, pull requests merged in 2022-07, with the labels that each got.

#3719 fix: Don't fail post processing compilation on non-ascii charmap
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
Labels: chore

#3734 change message of `/p remove <player>` if player does not need to be removed
  Core/src/main/java/com/plotsquared/core/command/Remove.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#3695 Deprecate the static Permissions "util" class that is almost entirely superseded by methods in PermissionHolder instances themselves
  Core/src/main/java/com/plotsquared/core/util/Permissions.java
Labels: Developer

#3718 fix: improve handling of missing message files
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/load/CaptionLoader.java
Labels: Bugfix

#3745 fix: Add user friendly message for creationdate placeholder
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
Labels: Bugfix

#3746 Don't allow wall corals to dry
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix
