Repository IntellectualSites/PlotSquared, pull requests merged in 2022-11, with the labels that each got.

#3866 Fix item thrower/owner can be null
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener117.java
Labels: Bugfix

#3868 feat: check merge limits when completing auto-merge
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/command/Merge.java
Labels: Feature

#3838 fix: attempt to recover from IllegalStateException when restoring block tags
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/LimitedRegionWrapperQueue.java
Labels: Bugfix

#3872 chore: deprecate paper 1.13 listener as P2 effectively doesn't support 1.13
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener113.java
Labels: chore

#3867 feat: improve handling of null issues in plot analysis
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
Labels: Feature

#3876 Revert "feat: check merge limits when completing auto-merge (#3868)" - Fixes a bug in 6.10.4
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/command/Merge.java
Labels: Bug, Bugfix, Feature

#3844 feat: add a permission to override-allow a merge if the other plot's owner is offline
  Core/src/main/java/com/plotsquared/core/command/Merge.java
  Core/src/main/java/com/plotsquared/core/permissions/Permission.java
Labels: Feature
