Repository IntellectualSites/PlotSquared, pull requests merged in 2023-01, with the labels that each got.

#3898 Fix wrong plot id calculation for negative coordinates
  Core/src/main/java/com/plotsquared/core/generator/SquarePlotManager.java
Labels: Bugfix

#3914 Replace licenser with spotless
  HEADER.txt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore

#3915 Remove unused editorconfig rules
  .editorconfig
Labels: chore

#3916 Drop HTTP4J
  Bukkit/build.gradle.kts
  gradle/libs.versions.toml
Labels: Developer

#3917 Add source documentation to javadocs and add dependency tab
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
  Core/src/main/java/com/plotsquared/core/events/PlayerAutoPlotEvent.java
  javadocfooter.html
Labels: documentation

#3922 Officially deprecated BukkitPlayer#BukkitPlayer()
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayerManager.java
Labels: Developer

#3913 chore: Update a few deprecations
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/managers/MultiverseWorldManager.java
Labels: chore

#3921 Reduce `/plot home` overhead
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
  Core/src/main/java/com/plotsquared/core/util/query/GlobalPlotProvider.java
Labels: Bugfix

#3930 Remove uses of deprecated `Permissions` class and add javadoc notes
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ForceFieldListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitOfflinePlayer.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitEntityUtil.java
  Core/src/main/java/com/plotsquared/core/command/Add.java
  Core/src/main/java/com/plotsquared/core/command/Alias.java
  Core/src/main/java/com/plotsquared/core/command/Area.java
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/command/Backup.java
  Core/src/main/java/com/plotsquared/core/command/Caps.java
  Core/src/main/java/com/plotsquared/core/command/Claim.java
  Core/src/main/java/com/plotsquared/core/command/Clear.java
  Core/src/main/java/com/plotsquared/core/command/Cluster.java
  Core/src/main/java/com/plotsquared/core/command/Command.java
  Core/src/main/java/com/plotsquared/core/command/Continue.java
  Core/src/main/java/com/plotsquared/core/command/Copy.java
  Core/src/main/java/com/plotsquared/core/command/Delete.java
  Core/src/main/java/com/plotsquared/core/command/Deny.java
  Core/src/main/java/com/plotsquared/core/command/Dislike.java
  Core/src/main/java/com/plotsquared/core/command/Done.java
  Core/src/main/java/com/plotsquared/core/command/Download.java
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
  Core/src/main/java/com/plotsquared/core/command/Grant.java
  Core/src/main/java/com/plotsquared/core/command/HomeCommand.java
  Core/src/main/java/com/plotsquared/core/command/Inbox.java
  Core/src/main/java/com/plotsquared/core/command/Info.java
  Core/src/main/java/com/plotsquared/core/command/Kick.java
  Core/src/main/java/com/plotsquared/core/command/Like.java
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/java/com/plotsquared/core/command/Load.java
  Core/src/main/java/com/plotsquared/core/command/MainCommand.java
  Core/src/main/java/com/plotsquared/core/command/Merge.java
  Core/src/main/java/com/plotsquared/core/command/Move.java
  Core/src/main/java/com/plotsquared/core/command/Music.java
  Core/src/main/java/com/plotsquared/core/command/Owner.java
  Core/src/main/java/com/plotsquared/core/command/Rate.java
  Core/src/main/java/com/plotsquared/core/command/Remove.java
  Core/src/main/java/com/plotsquared/core/command/Save.java
  Core/src/main/java/com/plotsquared/core/command/SchematicCmd.java
  Core/src/main/java/com/plotsquared/core/command/Set.java
  Core/src/main/java/com/plotsquared/core/command/SetCommand.java
  Core/src/main/java/com/plotsquared/core/command/Swap.java
  Core/src/main/java/com/plotsquared/core/command/Template.java
  Core/src/main/java/com/plotsquared/core/command/Trust.java
  Core/src/main/java/com/plotsquared/core/command/Unlink.java
  Core/src/main/java/com/plotsquared/core/command/Visit.java
  Core/src/main/java/com/plotsquared/core/components/ComponentPresetManager.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/java/com/plotsquared/core/listener/WESubscriber.java
  Core/src/main/java/com/plotsquared/core/permissions/PermissionHolder.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/java/com/plotsquared/core/plot/comment/CommentInbox.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
  Core/src/main/java/com/plotsquared/core/util/Permissions.java
Labels: chore

#3928 Separate workflows between PRs and pushes
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
Labels: chore

#3932 Default to unix line endings
  .gitattributes
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitWorld.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/fawe/FaweSchematicHandler.java
  Core/src/main/java/com/plotsquared/core/command/DebugExec.java
  Core/src/main/java/com/plotsquared/core/plot/PlotWorld.java
  Core/src/main/java/com/plotsquared/core/plot/flag/PlotFlag.java
  Core/src/main/java/com/plotsquared/core/util/RegionUtil.java
  Core/src/main/java/com/plotsquared/core/util/TabCompletions.java
  Core/src/main/java/com/plotsquared/core/util/net/AbstractDelegateOutputStream.java
  Core/src/main/java/com/plotsquared/core/util/query/OwnersIncludeFilter.java
  Core/src/main/java/com/plotsquared/core/util/task/PlotSquaredTask.java
  Core/src/test/java/com/plotsquared/core/database/AbstractDBTest.java
  build.gradle.kts
Labels: chore

#3937 Terminate process if `.git` folder is not a repository
  build.gradle.kts
Labels: skip-changelog

#3934 fix: Remove chunk#isLoaded call in BukkitChunkCoordinator
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitChunkCoordinator.java
Labels: Bugfix

#3935 fix: account for exclusivity of max build height where requires
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotManager.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/util/WEManager.java
Labels: Bugfix

#3933 fix: ensure plots are fully unlinked before the clear itself is run
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
Labels: Bugfix

#3941 chore: Remove things marked as for removal
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BlockStatePopulator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener113.java
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayerManager.java
  Bukkit/src/main/java/com/plotsquared/bukkit/schematic/StateWrapper.java
  Core/src/main/java/com/plotsquared/core/events/PlayerAutoPlotEvent.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
  Core/src/main/java/com/plotsquared/core/plot/PlotId.java
  Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
  Core/src/main/java/com/plotsquared/core/util/Permissions.java
Labels: chore

#3952 Make farmland keep its moisture
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Enhancement
