Repository IntellectualSites/PlotSquared, pull requests merged in 2023-10, with the labels that each got.

#4178 Address deprecated URL instantiation
  Bukkit/src/main/java/com/plotsquared/bukkit/util/UpdateUtility.java
  Core/src/main/java/com/plotsquared/core/PlotSquared.java
  Core/src/main/java/com/plotsquared/core/command/Load.java
  Core/src/main/java/com/plotsquared/core/command/SchematicCmd.java
  Core/src/main/java/com/plotsquared/core/util/SchematicHandler.java
Labels: hacktoberfest-accepted, Bugfix

#4177 Fix `#isAccessible()` deprecation in `HybridPlotWorld`
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
Labels: hacktoberfest-accepted, Bugfix

#4179 Addresses issues related to maven publish scm block
  build.gradle.kts
Labels: hacktoberfest-accepted, Bugfix

#4191 Address deprecated 'Project.buildDir' in build scripts
  Core/build.gradle.kts
Labels: hacktoberfest-accepted, chore

#4187 Update Paper javadoc URL to 1.20
  .github/ISSUE_TEMPLATE/bug_report.yml
  Bukkit/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: hacktoberfest-accepted, chore

#4194 Fix 'ChunkCoordinatorBuilder#unloadAfter()' javadocs
  Core/src/main/java/com/plotsquared/core/queue/ChunkCoordinatorBuilder.java
Labels: hacktoberfest-accepted, chore

#4181 feat: add placeholder for plot size
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
Labels: hacktoberfest-accepted, Feature

#4184 feat: add concrete-harden flag
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/ConcreteHardenFlag.java
  Core/src/main/resources/lang/messages_en.json
Labels: hacktoberfest-accepted, Feature

#4195 Migrate 'EntityUtil#capNumeral' to an enhanced switch
  Core/src/main/java/com/plotsquared/core/util/EntityUtil.java
Labels: hacktoberfest-accepted, chore

#4197 Fix: No response to errors in plot user group modifications
  Core/src/main/java/com/plotsquared/core/command/Add.java
  Core/src/main/java/com/plotsquared/core/command/CommandCategory.java
  Core/src/main/java/com/plotsquared/core/command/Deny.java
  Core/src/main/java/com/plotsquared/core/command/Owner.java
  Core/src/main/java/com/plotsquared/core/command/Trust.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/Caption.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/StaticCaption.java
  Core/src/main/java/com/plotsquared/core/configuration/caption/TranslatableCaption.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/plot/PlotModificationManager.java
  Core/src/main/java/com/plotsquared/core/util/PlayerManager.java
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
Labels: hacktoberfest-accepted, Bugfix

#4199 Default to latest version of informative-annotations
  Core/build.gradle.kts
Labels: chore

#4186 fix: load flags after we is initialised
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/resources/lang/messages_en.json
Labels: hacktoberfest-accepted, Bugfix

#4193 Replace deprecated ageable with breedable
  Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java
Labels: hacktoberfest-accepted, Bugfix

#4180 chore: remove poorly implemented /ps debug loadedchunks command
  Core/src/main/java/com/plotsquared/core/command/Debug.java
Labels: hacktoberfest-accepted, chore

#4207 Address deprecated 'Times#of()' in 'PlotPlayer'
  Core/build.gradle.kts
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
Labels: hacktoberfest-accepted, chore

#4218 Fix: including "highestLimit" number
  Core/src/main/java/com/plotsquared/core/util/TabCompletions.java
Labels: hacktoberfest-accepted, Bugfix

#4216 Delay economy initialization to server load
  Bukkit/src/main/java/com/plotsquared/bukkit/inject/BukkitModule.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ServerListener.java
Labels: hacktoberfest-accepted, Bugfix

#4213 feat: add configurable border size
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Core/src/main/java/com/plotsquared/core/command/Claim.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
Labels: hacktoberfest-accepted, Feature
