Repository IntellectualSites/PlotSquared, pull requests merged in 2023-04, with the labels that each got.

#4011 Fix Misaligned SVG In IJ project view
  .idea/icon.svg
Labels: chore

#3991 fix: clear above and below plot gen heights if build heights are larger
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotManager.java
Labels: Bugfix

#4014 fix: account for false permissions when checking range
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
Labels: Bugfix

#4018 Improve testability for different versions
  .gitignore
  build.gradle.kts
Labels: Feature

#4025 Fix `/plot area create <name>` without passing a specific terrain type
  Core/src/main/java/com/plotsquared/core/setup/PlotAreaBuilder.java
Labels: Bugfix
