Repository IntellectualSites/PlotSquared, pull requests merged in 2023-03, with the labels that each got.

#3976 Record-inize methods
  Bukkit/src/main/java/com/plotsquared/bukkit/placeholder/MVdWPlaceholders.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/GenChunk.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitSetupUtils.java
  Bukkit/src/main/java/com/plotsquared/bukkit/uuid/SQLiteUUIDService.java
  Core/src/main/java/com/plotsquared/core/backup/SimpleBackupManager.java
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/command/Inbox.java
  Core/src/main/java/com/plotsquared/core/command/ListCmd.java
  Core/src/main/java/com/plotsquared/core/command/Purge.java
  Core/src/main/java/com/plotsquared/core/command/Template.java
  Core/src/main/java/com/plotsquared/core/components/ComponentPreset.java
  Core/src/main/java/com/plotsquared/core/components/ComponentPresetManager.java
  Core/src/main/java/com/plotsquared/core/database/SQLManager.java
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
  Core/src/main/java/com/plotsquared/core/location/ChunkWrapper.java
  Core/src/main/java/com/plotsquared/core/plot/BlockBucket.java
  Core/src/main/java/com/plotsquared/core/plot/PlotSettings.java
  Core/src/main/java/com/plotsquared/core/plot/comment/CommentManager.java
  Core/src/main/java/com/plotsquared/core/plot/comment/PlotComment.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/FeedFlag.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/HealFlag.java
  Core/src/main/java/com/plotsquared/core/plot/flag/types/TimedFlag.java
  Core/src/main/java/com/plotsquared/core/services/plots/AutoQuery.java
  Core/src/main/java/com/plotsquared/core/services/plots/AutoService.java
  Core/src/main/java/com/plotsquared/core/setup/SettingsNodeStep.java
  Core/src/main/java/com/plotsquared/core/setup/SettingsNodesWrapper.java
  Core/src/main/java/com/plotsquared/core/util/FileBytes.java
  Core/src/main/java/com/plotsquared/core/util/PlayerManager.java
  Core/src/main/java/com/plotsquared/core/util/TabCompletions.java
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
  Core/src/main/java/com/plotsquared/core/uuid/CacheUUIDService.java
  Core/src/main/java/com/plotsquared/core/uuid/UUIDMapping.java
  Core/src/main/java/com/plotsquared/core/uuid/UUIDPipeline.java
Labels: Breaking change

#3978 Fix farmland moisturize
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix

#3977 Deprecate unused methods for removal
  Core/src/main/java/com/plotsquared/core/configuration/Config.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/plot/PlotSettings.java
  Core/src/main/java/com/plotsquared/core/util/BlockUtil.java
  Core/src/main/java/com/plotsquared/core/util/ChunkUtil.java
  Core/src/main/java/com/plotsquared/core/util/MathMan.java
  Core/src/main/java/com/plotsquared/core/util/RegionUtil.java
  Core/src/main/java/com/plotsquared/core/util/StringMan.java
  Core/src/main/java/com/plotsquared/core/util/WEManager.java
Labels: Developer

#3979 Migrate left over occurrences to enhanced switches
  Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Core/src/main/java/com/plotsquared/core/command/Clear.java
  Core/src/main/java/com/plotsquared/core/command/Cluster.java
  Core/src/main/java/com/plotsquared/core/command/Command.java
  Core/src/main/java/com/plotsquared/core/command/DebugRoadRegen.java
  Core/src/main/java/com/plotsquared/core/command/Help.java
  Core/src/main/java/com/plotsquared/core/command/Inbox.java
  Core/src/main/java/com/plotsquared/core/command/Purge.java
  Core/src/main/java/com/plotsquared/core/generator/SquarePlotManager.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/DenyTeleportFlag.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/FlyFlag.java
  Core/src/main/java/com/plotsquared/core/queue/subscriber/DefaultProgressSubscriber.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
Labels: chore

#3980 Cleanup deprecated methods
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitPlotGenerator.java
  Core/src/main/java/com/plotsquared/core/configuration/Config.java
  Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/plot/PlotSettings.java
  Core/src/main/java/com/plotsquared/core/util/BlockUtil.java
  Core/src/main/java/com/plotsquared/core/util/ChunkUtil.java
  Core/src/main/java/com/plotsquared/core/util/MathMan.java
  Core/src/main/java/com/plotsquared/core/util/RegionUtil.java
  Core/src/main/java/com/plotsquared/core/util/StringMan.java
  Core/src/main/java/com/plotsquared/core/util/WEManager.java
Labels: Breaking change
