Repository IntellectualSites/PlotSquared, pull requests merged in 2023-06, with the labels that each got.

#4044 Update gradle to 8
  .github/workflows/codeql.yml
  Bukkit/build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#4055 Update top level group Id
  build.gradle.kts
Labels: Breaking changes

#4060 Update top level group id and lowercaswe artifact names
  Bukkit/build.gradle.kts
  build.gradle.kts
  settings.gradle.kts
Labels: Breaking changes

#4016 Wrong biome list for 1.19.4 if datapacks are not enabled
  Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitPlotGenerator.java
Labels: Bugfix

#4061 Add support for 1.20
  .github/ISSUE_TEMPLATE/bug_report.yml
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
  Core/src/main/java/com/plotsquared/core/command/Music.java
  Core/src/main/java/com/plotsquared/core/configuration/file/YamlConstructor.java
  Core/src/main/java/com/plotsquared/core/configuration/file/YamlRepresenter.java
  build.gradle.kts
Labels: Major feature

#4077 Strip legacy color codes if message cannot be parsed by MiniMessage
  Core/src/main/java/com/plotsquared/core/configuration/caption/CaptionUtility.java
Labels: Bugfix

#4085 fix: return on null plot on big boom
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix
