Repository IntellectualSites/PlotSquared, pull requests merged in 2023-08, with the labels that each got.

#4132 fix: remove "default" spawn reason
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
Labels: Bugfix

#4126 feat: allow bypass of econ costs
  Core/src/main/java/com/plotsquared/core/command/Auto.java
  Core/src/main/java/com/plotsquared/core/command/Claim.java
  Core/src/main/java/com/plotsquared/core/command/MainCommand.java
  Core/src/main/java/com/plotsquared/core/command/Merge.java
  Core/src/main/java/com/plotsquared/core/components/ComponentPresetManager.java
  Core/src/main/java/com/plotsquared/core/permissions/Permission.java
Labels: Feature

#4148 Remove repository-level CoC in favor with organization-level CoC
  CODE_OF_CONDUCT.md
Labels: skip-changelog
