Repository IntellectualSites/PlotSquared, pull requests merged in 2023-12, with the labels that each got.

#4255 Declare explicit runtime dependency on 'junit-platform-launcher'
  build.gradle.kts
Labels: chore

#4259 feat: add HasOwner PlotFilter filter
  Core/src/main/java/com/plotsquared/core/util/query/HasOwnerFilter.java
  Core/src/main/java/com/plotsquared/core/util/query/PlotQuery.java
Labels: Feature

#4185 feat: add projectile-change-block flag
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/ProjectileChangeBlockFlag.java
  Core/src/main/resources/lang/messages_en.json
Labels: hacktoberfest-accepted, Feature

#4267 feat: Allow admin done permission to override requiring plot complexity calculation
  Core/src/main/java/com/plotsquared/core/command/Done.java
Labels: Feature

#4261 feat: allow for custom plot limit handling
  Core/src/main/java/com/plotsquared/core/events/PlayerPlotLimitEvent.java
  Core/src/main/java/com/plotsquared/core/player/PlotPlayer.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
Labels: Feature

#4260 refactor: move leave event dispact to after logic
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
Labels: chore

#4257 fix: allow pistons on merged plot road if detect-invalid-edge-pistons true
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
Labels: Bugfix
