Repository IntellectualSites/PlotSquared, pull requests merged in 2023-11, with the labels that each got.

#4226 Add info about service providers to debugpaste
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
Labels: Feature

#4231 Fix: chest_boat not removing
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
Labels: Bugfix

#4106 Fix: remove everyone command
  Core/src/main/java/com/plotsquared/core/command/Remove.java
Labels: Bugfix

#4239 Make '/plot download world' clickable
  Core/src/main/java/com/plotsquared/core/command/Download.java
Labels: Bugfix

#4217 Fix: permission check for integer flags
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
  Core/src/main/java/com/plotsquared/core/command/FlagCommand.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/permissions/PermissionHolder.java
Labels: Bugfix

#4196 Feat(API): Mutable Location in PlayerTeleportToPlotEvent
  Core/src/main/java/com/plotsquared/core/events/PlayerTeleportToPlotEvent.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
Labels: hacktoberfest-accepted, Feature

#4240 fix: re-add default spawn option and disclude armour stands
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
Labels: Bugfix

#4236 Introduce `edit-sign` flag
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener1201.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/EditSignFlag.java
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
  Core/src/main/resources/lang/messages_en.json
  build.gradle.kts
Labels: Feature
