Repository IntellectualSites/PlotSquared, pull requests merged in 2024-03, with the labels that each got.

#4343 feat: introduce a fishing flag
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/FishingFlag.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#4368 feat: introduce a flag section into the config for instabreak
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
Labels: Feature

#4370 Prevent loading faraway chunks
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
  Core/src/main/java/com/plotsquared/core/command/MainCommand.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/util/WorldUtil.java
Labels: Bugfix

#4376 Drop support for 1.17.1 and prior
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
Labels: skip-changelog

#4219 Feat: adding "last" argument for Visit cmd to choose the highest number
  Core/src/main/java/com/plotsquared/core/command/Visit.java
Labels: Feature

#4371 Introduce tile-drop flag
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java
  Core/src/main/java/com/plotsquared/core/plot/flag/implementations/TileDropFlag.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#4355 fix-armor-stand-caps
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
Labels: Bugfix

#4336 fix: allow trusted players to remove books from lecterns while lectern-read-book flag is true
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix

#4380 Add a placeholder for grants
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
Labels: Enhancement
