Repository IntellectualSites/PlotSquared, pull requests merged in 2024-04, with the labels that each got.

#4391 fix plot music volume to span full plot
  Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayer.java
Labels: Bugfix

#4388 fix: skip valid location check for world plots
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/plot/world/SinglePlotManager.java
Labels: Bugfix

#4395 Make builds reproducible
  Bukkit/build.gradle.kts
  Core/build.gradle.kts
  build.gradle.kts
Labels: Developer

#4398 Introduce 'skip.signing' property
  build.gradle.kts
Labels: skip-changelog

#4407 Don't heal dead players
  Core/src/main/java/com/plotsquared/core/listener/PlotListener.java
Labels: Bugfix
