Repository IntellectualSites/PlotSquared, pull requests merged in 2024-02, with the labels that each got.

#4305 Entity#getEntitySpawnReason compatibility for spigot
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
Labels: chore

#4266 feat: configurable accounting for bedrock layer when setting components
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotManager.java
  Core/src/main/java/com/plotsquared/core/generator/ClassicPlotWorld.java
  Core/src/main/java/com/plotsquared/core/plot/PlotArea.java
  Core/src/main/resources/lang/messages_en.json
Labels: Feature

#4325 fix: allow allay breeding
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
Labels: Bugfix

#4328 Introduce base plot count placeholder
  Bukkit/src/main/java/com/plotsquared/bukkit/placeholder/PAPIPlaceholders.java
  Core/src/main/java/com/plotsquared/core/util/placeholders/PlaceholderRegistry.java
Labels: Feature

#4332 Avoid creating EntityDamageByEntityEvent
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
Labels: Bugfix

#4334 Suppress errors due to failed getEntitySpawnReason implementation
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
Labels: Bugfix

#4341 Remove static print out of legacy schematic URL
  Core/src/main/java/com/plotsquared/core/command/Download.java
Labels: Bugfix

#4345 return false if PLACE_VEHICLE and missing flag
  Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
Labels: Bugfix
