Repository IntellectualSites/PlotSquared, pull requests merged in 2025-05, with the labels that each got.

#4640 Add server brand to debugpaste
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Core/src/main/java/com/plotsquared/core/PlotPlatform.java
  Core/src/main/java/com/plotsquared/core/command/DebugPaste.java
Labels: chore

#4632 Add 'world' placeholder to status messages
  Core/src/main/java/com/plotsquared/core/command/Buy.java
  Core/src/main/java/com/plotsquared/core/command/Clear.java
  Core/src/main/java/com/plotsquared/core/command/Delete.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/resources/lang/messages_en.json
Labels: Enhancement

#4651 chore/fix: use #getBlock in PlayerBucketEmptyEvent
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
Labels: Bugfix, chore

#4650 fix: cancel teleport to denied plot
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  build.gradle.kts
Labels: Bugfix

#4641 fix: Don't use list to proof block is copper. Instead check with name
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener117.java
Labels: Bugfix, Feature

#4653 fix: cancel structure locate in classic plot worlds
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
Labels: Bugfix
