Repository IntellectualSites/PlotSquared, pull requests merged in 2025-02, with the labels that each got.

#4369 Improve teleport behavior for home command
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitUtil.java
  Core/src/main/java/com/plotsquared/core/configuration/Settings.java
  Core/src/main/java/com/plotsquared/core/plot/Plot.java
  Core/src/main/java/com/plotsquared/core/util/WorldUtil.java
Labels: Feature

#4592 renewed fix: update error message of `/p remove <player>` if player does not need to be removed
  Core/src/main/java/com/plotsquared/core/command/Remove.java
Labels: Bugfix, Feature

#4582 1.21.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  Bukkit/build.gradle.kts
  Bukkit/src/main/java/com/plotsquared/bukkit/BukkitPlatform.java
  Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PaperListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/ProjectileEventListener.java
  Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitEntityUtil.java
  build.gradle.kts
Labels: Bugfix

#4599 fix: allow queues to not generate chunks
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitChunkCoordinator.java
  Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java
  Core/src/main/java/com/plotsquared/core/inject/factory/ChunkCoordinatorFactory.java
  Core/src/main/java/com/plotsquared/core/queue/ChunkCoordinatorBuilder.java
  Core/src/main/java/com/plotsquared/core/queue/DelegateQueueCoordinator.java
  Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java
Labels: Bugfix

#4522 Execute chunk loading operations outside the main thread
  Core/src/main/java/com/plotsquared/core/command/MainCommand.java
Labels: Feature

#4609 Fix IndexOutOfBoundsException on BlockFertilizeEvent
  Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener117.java
Labels: Bugfix
